version: "3"

services:
  pixetl_dev:
    build:
      context: .
    container_name: pixetl_dev
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - $HOME/.gsutil:/root/.gcs:ro
      - ./gfw_pixetl:/usr/local/app/gfw_pixetl:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./tmp:/tmp
    environment:
      - ENV=dev
      - PGPASSWORD=postgres  # pragma: allowlist secret
      - PGHOST=test_database
      - PGUSER=gfw
      - PGDATABASE=_test
      - AWS_DEFAULT_PROFILE=gfw-dev
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.gcs/private_key.json
      - DIVISOR=1
      - MAX_MEM=4000
      - CORES=2
#      - GCS_KEY_SECRET_ARN=gcs/gfw-gee-export
#      - AWS_ACCESS_KEY_ID=testing  # pragma: allowlist secret
#      - AWS_SECRET_ACCESS_KEY=testing  # pragma: allowlist secret
#      - AWS_SECURITY_TOKEN=testing  # pragma: allowlist secret
#      - AWS_SESSION_TOKEN=testing  # pragma: allowlist secret
#      - ENDPOINT_URL=http://motoserver:5000
#      - AWS_HTTPS=NO
#      - AWS_VIRTUAL_HOSTING=FALSE
#      - GDAL_DISABLE_READDIR_ON_OPEN=YES
    working_dir: /tmp
#    entrypoint: /bin/bash
    depends_on:
      - dev_database
#      - motoserver
  dev_database:
    container_name: pixetl-dev-database
    image: postgis/postgis:11-3.0-alpine
    ports:
      - 54323:5432
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=_test
      - POSTGRES_USER=gfw
      - POSTGRES_PASSWORD=postgres  # pragma: allowlist secret
    volumes:
      - dev_database_data:/var/lib/postgresql/data
    restart: on-failure

#  motoserver:
#    container_name: motoserver
#    image: motoserver/moto:latest
#    ports:
#      - 5000:5000
#    entrypoint: moto_server s3 -H 0.0.0.0
#    restart: on-failure

volumes:
  dev_database_data:
