#!/bin/bash

set -e


# Default values
POSITIONAL=()
BUILD=true
# extracting cmd line arguments
while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
      --no_build)
      BUILD=false
      shift # past argument
      ;;
      *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters


if [ "${BUILD}" = true ]; then
  docker-compose -f docker-compose.dev.yml --project-name gfw-pixetl_dev build pixetl_dev
fi

set +e
docker-compose -f docker-compose.dev.yml --project-name gfw-pixetl_dev run --rm --name pixetl_dev pixetl_dev "$@"
exit_code=$?
docker-compose -f docker-compose.dev.yml --project-name gfw-pixetl_dev down --remove-orphans
exit $exit_code
