#!/usr/bin/env bash

export PIPENV_IGNORE_VIRTUALENVS=1
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

pip install pipenv
pipenv install

pipenv run pip install -e .
pipenv run detect-secrets scan > .secrets.baseline
pipenv run pre-commit install
