#!/bin/bash

set -e


# Default values
POSITIONAL=()
BUILD=true
# extracting cmd line arguments
while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
      --no_build)
      BUILD=false
      shift # past argument
      ;;
      *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters


if [ "${BUILD}" = true ]; then
  docker-compose -f docker-compose.test.yml --project-name gfw-pixetl_test build sut
fi

set +e
docker-compose -f docker-compose.test.yml --project-name gfw-pixetl_test run --rm --name pixetl_test sut "$*"
exit_code=$?
docker-compose -f docker-compose.test.yml --project-name gfw-pixetl_test down --remove-orphans
rm tests/terraform/terraform.tfstate*
exit $exit_code
