#!/usr/bin/env bash

set -e

while getopts k:s: option
do
case "${option}"
in
k) AWS_ACCESS_KEY_ID=${OPTARG};;
s) AWS_SECRET_ACCESS_KEY=${OPTARG};;
esac
done

cur_dir=$(dirname "$0")
${cur_dir}/cibuild

# get current git branch and replace / with -
read -r cur_branch < <(git rev-parse --abbrev-ref HEAD | tr "/" "-")

if [ "$cur_branch" == "master" ] || [ "$cur_branch" == "develop" ]
then
  SUFFIX=""
else
  SUFFIX="-$cur_branch"
fi

docker run -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -v /tmp:/tmp -v ${PWD}/:/usr/local/app --entrypoint pytest pixetl${SUFFIX}  --cov-report term --cov-report xml --cov=. tests/  # pragma: allowlist secret
