#!/usr/bin/env bash

set -e

BRANCH=$(echo $(git rev-parse --abbrev-ref HEAD))

echo "Current branch: ${BRANCH}"

while getopts b:k:s: option; do
  case "${option}" in

  b) BRANCH=${OPTARG} ;;
  k) AWS_ACCESS_KEY_ID=${OPTARG} ;;
  s) AWS_SECRET_ACCESS_KEY=${OPTARG} ;;
  esac
done

echo "Branch set to: ${BRANCH}"

cur_dir=$(dirname "$0")
"${cur_dir}"/cibuild "${BRANCH}"

# replace / with -
read -r cur_branch < <(echo "${BRANCH}" | tr "/" "-")

# shellcheck disable=SC2109
if [ "$cur_branch" == "master" ] || [ "$cur_branch" == "develop" ]; then
  SUFFIX=""
else
  SUFFIX="-$cur_branch"
fi

AWS_PROFILE="gfw-dev" # For tests always use dev profile, even for master and develop branch, we need to access the test bucket

docker run -e AWS_DEFAULT_PROFILE=${AWS_PROFILE} \
            -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
            -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
            -e ENV="test" \
            -v /tmp:/tmp \
            -v "${PWD}"/:/usr/local/app \
            -v "${HOME}"/.aws:/root/.aws:ro \
            --entrypoint pytest pixetl"${SUFFIX}" \
            --cov-report term --cov-report xml --cov=/usr/local/app \
            /usr/local/app/tests/
