name: Plan terraform changes for base branch

on: [pull_request]

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Lambda layers
      run: ./scripts/cibuild ${{github.ref}}
    - name: Plan production
      if: success() && contains(github.base_ref, 'master')
      env:
        ENV: production
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_production }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_production }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_production }}
      run: ./scripts/infra plan ${{ github.base_ref }}
    - name: Plan staging
      if: success() && contains(github.base_ref, 'develop')
      env:
        ENV: staging
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_staging }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_staging }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_staging }}
      run: ./scripts/infra plan ${{ github.base_ref }}
    - name: Plan dev
      if: success() && (! contains(github.base_ref, 'master')) && (! contains(github.base_ref, 'develop'))
      env:
        ENV: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_dev }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_dev }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_dev }}
      run: ./scripts/infra plan ${{ github.base_ref }}
